server:
  port: 8089  # Port for chat-service

spring:
  application:
    name: chat-service
  config:
    import: optional:configserver:http://localhost:8086
  datasource:
    url: jdbc:postgresql://localhost:5433/chat_db
    username: postgres
    password: postgres
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka