server:
  port: 8086

spring:
  application:
    name: config-service
  cloud:
    config:
      server:
        git:
          uri: https://github.com/Abhishek3842/Config_Service.git
          default-label: main
