server:
  port: 8088
spring:
  application:
    name: lawyers-service

  datasource:
    url: jdbc:postgresql://localhost:5433/lawyer_db
    username: postgres
    password: postgres
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka