server:
  port: 8088
spring:
  application:
    name: lawyers-service
  config:
    import: optional:configserver:http://localhost:8086
  datasource:
    url: jdbc:postgresql://localhost:5432/lawyer_db
    username: postgres
    password: postgres
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka