server:
  port: 8083

spring:
  application:
    name: pdf-service

  datasource:
    url: jdbc:postgresql://localhost:5433/pdf_db
    username: postgres
    password: postgres
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/
